version: '2'
services:
  data:
    image: sajidmomin/digitalx-data:latest
  redis:
    image: redis
    mem_limit: 200m
  db:
    image: sajidmomin/digitalx-mysql:latest
    mem_limit: 700m
    volumes_from:
      - data
  dxm:
    image: sajidmomin/digitalx:latest
    mem_limit: 4096m
    volumes_from:
      - data
    links:
      - db:mysql
      - redis:redis
    ports:
      - 9088:8080
  web:
    image: sajidmomin/digitalx-nginx:latest
    mem_limit: 500m
    links:
      - dxm:node1
    ports:
      - 80:80
      - 443:443