---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=3600

- name: Add vagrant user to docker group.
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes